# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f1e5f2c2cb7734af3af9af194045827c0a47a7a7181d77d66c6eae92266b6bd3d243988a8b8057c3e045df310520bcbfd93d98b14f3efd4a1904c68bfd188c

test:
  secret_key_base: bd681a0df0b931de1f0c9ed2f0ec9098a4cca0aa0a9c05400f0f1e6421583d513b18f5926b346589c039c832f161c58932adf519950c740113ce9e5168a16021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
